# Generated by Django 5.1.1 on 2024-09-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='track_path',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles'),
        ),
    ]
