# Generated by Django 5.1.1 on 2024-09-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_subtitle_track_path_subtitle_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='file',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='subtitle_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
